### ISSUE TITLE
Stable fit with 2 neighbors

### ISSUE THREAD

**Issue by ThibaultLejemble** [poncateam/ponca#100]
Hello, 
I found a situation where the fit result is set to `STABLE`, but the number of neighbors is equal to `2`.
It seems to be in contradiction with the documentation that says: `The fitting is stable an ready to use (and having more than 6 neighbours)` 
https://github.com/poncateam/ponca/blob/e24146e1c599debd7ec9a2a6911c0bfe1a7e94ba/Ponca/src/Fitting/enums.h#L16

Is the documentation correct? 
If it is correct I'll check what makes the status as stable.

Here is the example I am using: 

```c++
#include <Ponca/Fitting>
#include <iostream>
#include "Eigen/Eigen"

using namespace Ponca;

class Point
{
public:
  enum {Dim = 3};
  using Scalar = float;
  using VectorType = Eigen::Matrix<Scalar, Dim, 1>;
  using MatrixType = Eigen::Matrix<Scalar, Dim, Dim>;

  inline Point(
    const VectorType& pos,
    const VectorType& normal)
    : m_pos(pos), m_normal(normal) 
    {}

  inline const VectorType& pos()    const {return m_pos;}
  inline       VectorType& pos()          {return m_pos;}
  inline const VectorType& normal() const {return m_normal;}
  inline       VectorType& normal()       {return m_normal;}

protected:
  VectorType m_pos, m_normal;
};

using Scalar = Point::Scalar;
using Vector = Point::VectorType;

using WeightFunc = DistWeightFunc<
  Point,
  SmoothWeightKernel<Scalar>>;

using Fit0 = Ponca::Basket<
  Point, 
  WeightFunc, 
  Ponca::OrientedSphereFit,
  Ponca::GLSParam>;

using FitSphere = Ponca::BasketDiff<
  Fit0, 
  Ponca::FitScaleSpaceDer,
  Ponca::OrientedSphereDer,
  Ponca::MlsSphereFitDer,
  Ponca::CurvatureEstimatorBase,
  Ponca::NormalDerivativesCurvatureEstimator,
  Ponca::GLSDer>;

std::string to_string(FIT_RESULT res)
{
  switch (res)
  {
  case STABLE: return "STABLE";
  case UNSTABLE: return "UNSTABLE";
  case UNDEFINED: return "UNDEFINED";
  case NEED_OTHER_PASS: return "NEED_OTHER_PASS";
  case CONFLICT_ERROR_FOUND: return "CONFLICT_ERROR_FOUND";
  default: return "";
  }
}

int main()
{
  FitSphere fit;
  fit.setWeightFunc(WeightFunc(0.156472));
  fit.init(Vector(-81.265, 14.065, -15.562));
  const bool added0 = fit.addNeighbor(Point(Vector(-81.265, 14.065, -15.562), Vector(-0.0301018, -0.881152, -0.471874).normalized()));
  const bool added1 = fit.addNeighbor(Point(Vector(-81.172, 14.091, -15.476), Vector(0.265552, 0.913963, 0.306844).normalized()));
  const FIT_RESULT result = fit.finalize();
  const FIT_RESULT status = fit.getCurrentState();

  std::cout << "added 0   = " << std::boolalpha << added0 << std::endl;
  std::cout << "added 1   = " << std::boolalpha << added1 << std::endl;
  std::cout << "result    = " << to_string(result) << std::endl;
  std::cout << "status    = " << to_string(status) << std::endl;
  std::cout << "nei_count = " << fit.getNumNeighbors() << std::endl;
  std::cout << "sum_w     = " << fit.getWeightSum() << std::endl;
}

```
which outputs:
```
added 0   = true
added 1   = true
result    = STABLE
status    = STABLE
nei_count = 2
sum_w     = 1.10051
```

**Comment by nmellado** [comment]
Hello @ThibaultLejemble ,

Thanks for the report,
Yes indeed, two neighbors are not enough, the fit should not be stable.
Feel free to assign you the issue if you can fix it.

**Comment by ThibaultLejemble** [comment]
During the finalize phase, the `PrimitiveBase` only checks if there is at least 1 neighbor 
https://github.com/poncateam/ponca/blob/0a48bd0b09cc2a1a5cb94be4bf07a40ff5459adc/Ponca/src/Fitting/primitive.h#L123
If there is 2 neighbors the `m_eCurrentState` is set to `STABLE`.

Then the `OrientedSphereFitImpl` checks if there is at least 3 neighbors 
https://github.com/poncateam/ponca/blob/0a48bd0b09cc2a1a5cb94be4bf07a40ff5459adc/Ponca/src/Fitting/orientedSphereFit.hpp#L44
If it is not the case, like if there is 2 neighbors, it returns the `m_eCurrentState` which has been set to `STABLE`, whereas it should be set to `UNDEFINED`. 


One solution could be to split the test 
https://github.com/poncateam/ponca/blob/0a48bd0b09cc2a1a5cb94be4bf07a40ff5459adc/Ponca/src/Fitting/orientedSphereFit.hpp#L44C01-L45C37
in two tests:
```c++
if(Base::finalize() != STABLE) //  || Base::getNumNeighbors() < 3) 
    return Base::m_eCurrentState;
if(Base::getNumNeighbors() < 3)
    return Base::m_eCurrentState = UNDEFINED;
```

**Comment by nmellado** [comment]
Ok, makes sense...
It seems a good idea that `STABLE` status only can be overridden, or must be when computations are done.

And I guess we have the same issue at several other locations, could you please check this ?

**Comment by ThibaultLejemble** [comment]
Indeed, all the sphere fitting procedures have this same issue.

I am not sure to understand the doc
```c++
/*! \brief The fitting is ready to use but it can be unstable (and
    having between 3 and 6 neighbors)*/
UNSTABLE  = 1,
```
does it mean that if the number of neighbors is between 3 and 6, then the status is **necessarily** set to `UNSTABLE` ? Or it means that a fitting procedure **can** return `UNSTABLE` and in that case the number of neighbors is necessarily between 3 and 6 ?

I also found that `CovarianceLineFitImpl` does not check for `CONFLICT_ERROR_FOUND` as done in all other fitting classes.
