### ISSUE TITLE
Algebraic Sphere gradient is normalized

### ISSUE THREAD

**Issue by ThibaultLejemble** [poncateam/ponca#118]
I think this is an error
```c++
PONCA_MULTIARCH inline VectorType primitiveGradient () const { return m_ul.normalized(); }
```
https://github.com/poncateam/ponca/blob/f8e54a568fe54b9ed78eb612b9ec97101c79df80/Ponca/src/Fitting/algebraicSphere.h#L252C8-L252C8

The gradient of a primitive should be different than the normal vector and should not be normalized?

But without the normalization, the test `gls_paraboloid_der` is broken.
If the gradient should not be normalized, then I'll check what is the issue with this test.

**Comment by nmellado** [comment]
True, there is an issue here: `primitiveGradient` was initially designed as being an accessor to the local surface normal (thus the normalization). But the name tells something else, and as you said, there is no reason to have the scalar field normalized.

My suggestion is to clarify the API and separate `normal` and `gradient`. This is somehow related to the local frame considered here https://github.com/poncateam/ponca/pull/79.
