### ISSUE TITLE
Ponca not working as submodule

### ISSUE THREAD

**Issue by dcoeurjo** [poncateam/ponca#15]
When using ponca a submodule, the cmake outputs some errors (not tested using `fetch_content`). Have you experienced similar issues?

**Comment by dcoeurjo** [comment]
Have you already tested ponca as Fetchcontent?

**Comment by nmellado** [comment]
Just to be sure I can reproduce the problem, can you post here a sample cmake file showing how you use the library ?

**Comment by dcoeurjo** [comment]
WIP in #16 
thx @nmellado ;)

**Comment by nmellado** [comment]
Waiting for CI to finish in #16, should be fixed now.
